import './scss/styles.scss'
import * as bootstrap from 'bootstrap'
import particles from 'particles.js'
import './js/particles.js'
import './js/main.js'
import '../node_modules/typed.js/dist/typed.umd.js'